version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: weekly
      time: "03:14"
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: weekly
      time: "04:35"
    open-pull-requests-limit: 10
